INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (1, 'CBSE', 1);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (2, 'ICSE', 1);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (3, 'IB', 1);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (4, 'State board', 1);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (5, 'Indian Institute of Science, Bangalore', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (6, 'Indian Institute of Technology, Kharagpur', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (7, 'Indian Institute of Technology, Roorkee', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (8, 'Indian Institute of Technology, Kanpur', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (9, 'National Institute of Pharmaceutical Education and Research, Mohali', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (10, 'VIT University, Vellore', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (11, 'University of Delhi, Delhi', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (12, 'Indian Institute of Technology, Bombay', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (13, 'Indian Institute of Technology, Delhi', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (14, 'Tata Institute of Fundamental Research, Mumbai', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (15, 'Indian Institute of Technology, Guwahati', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (16, 'Anna University, Chennai', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (17, 'Panjab University, Chandigarh', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (18, 'Indian Institute of Technology, Madras', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (19, 'Jawaharlal Nehru Centre for Advanced Scientific Research, Bangalore', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (20, 'All India Institute of Medical Sciences, New Delhi', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (21, 'Jadavpur University, Kolkata', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (22, 'Banaras Hindu University, Varanasi', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (23, 'Institute of Chemical Technology, Mumbai', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (24, 'Postgraduate Institute of Medical Education and Research, Chandigarh', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (25, 'Aligarh Muslim University, Aligarh', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (26, 'University of Calcutta, Kolkata', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (27, 'University of Hyderabad, Hyderabad', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (28, 'SASTRA University, Thanjavur', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (29, 'Bharathiar University, Coimbatore', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (30, 'Sanjay Gandhi Postgraduate Institute of Medical Sciences, Lucknow', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (31, 'Indian Institute of Science Education and Research, Pune', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (32, 'Indian Institute of Technology, Indore', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (33, 'Jawaharlal Nehru University, New Delhi', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (34, 'National Institute of Technology, Tiruchirappalli', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (35, 'Indian Institute of Science Education and Research, Kolkata', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (36, 'Annamalai University, Annamalai Nagar', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (37, 'Visva Bharati, Santinikaten', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (38, 'Indian Institute of Science Education and Research, Thiruvananthapuram', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (39, 'National Institute of Technology, Rourkela', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (40, 'Guru Nanak Dev University, Amritsar', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (41, 'University of Madras, Chennai', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (42, 'University of Rajasthan, Jaipur', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (43, 'University of Jammu, Jammu', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (44, 'Bharathidasan University, Tiruchirappalli', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (45, 'Shivaji University, Kolhapur', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (46, 'Indian Institute of Science Education and Research, Mohali', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (47, 'Indian Statistical Institute, Kolkata', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (48, 'University of Pune, Pune', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (49, 'Indian Agricultural Research Institute, New Delhi', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (50, 'Tezpur University, Tezpur', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (51, 'National Brain Research Centre, Gurgaon', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (52, 'Madurai Kamaraj University, Madurai', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (53, 'Indian Institute of Technology, Ropar', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (54, 'Sri Venkateswara University, Tirupati', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (55, 'University of Allahabad, Allahabad', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (56, 'University of Burdwan, Bardhaman', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (57, 'Pondicherry University, Puducherry', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (58, 'Thapar University, Patiala', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (59, 'National Institute of Mental Health and Neuro Sciences, Bangalore', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (60, 'Indian Institute of Engineering Science and Technology, Shibpur', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (61, 'Jawaharlal Nehru Technological University, Hyderabad', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (62, 'National Institute of Technology, Durgapur', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (63, 'Sree Chitra Tirunal Institute for Medical Sciences and Technology, Thiruvananthapuram', 2);
INSERT INTO ojp.organization (organization_id, organization, organization_type_id) VALUES (64, 'Birla Institute of Technology and Science, Pilani', 2);