INSERT INTO ojp.designations (designation_id, designation) VALUES (1, 'Module Lead');
INSERT INTO ojp.designations (designation_id, designation) VALUES (2, 'Team Lead');
INSERT INTO ojp.designations (designation_id, designation) VALUES (3, 'Senior Team Lead');
INSERT INTO ojp.designations (designation_id, designation) VALUES (4, 'Account Manager');
INSERT INTO ojp.designations (designation_id, designation) VALUES (5, 'Architect');
INSERT INTO ojp.designations (designation_id, designation) VALUES (6, 'Technical Specialist');
INSERT INTO ojp.designations (designation_id, designation) VALUES (7, 'Delivery Manager');
INSERT INTO ojp.designations (designation_id, designation) VALUES (8, 'Delivery Head');
INSERT INTO ojp.designations (designation_id, designation) VALUES (9, 'Business Analyst');
INSERT INTO ojp.designations (designation_id, designation) VALUES (10, 'Delivery Partner');
INSERT INTO ojp.designations (designation_id, designation) VALUES (11, 'associate');
INSERT INTO ojp.designations (designation_id, designation) VALUES (12, 'software Engineer');
INSERT INTO ojp.designations (designation_id, designation) VALUES (13, 'senior Software Engineer');
INSERT INTO ojp.designations (designation_id, designation) VALUES (14, 'team Lead/Technical Lead');
INSERT INTO ojp.designations (designation_id, designation) VALUES (15, 'Project Manager/Project Lead/Technical Architect');
INSERT INTO ojp.designations (designation_id, designation) VALUES (16, 'senior PM/Senior PL');
INSERT INTO ojp.designations (designation_id, designation) VALUES (17, 'associate Director(Purely managerial)');
INSERT INTO ojp.designations (designation_id, designation) VALUES (18, 'director');
INSERT INTO ojp.designations (designation_id, designation) VALUES (19, 'associate Vice President(AVP)');
INSERT INTO ojp.designations (designation_id, designation) VALUES (20, 'vice-President');
INSERT INTO ojp.designations (designation_id, designation) VALUES (21, 'chief Executive Officer.');
INSERT INTO ojp.designations (designation_id, designation) VALUES (22, 'associate HR');
INSERT INTO ojp.designations (designation_id, designation) VALUES (23, 'executive');
INSERT INTO ojp.designations (designation_id, designation) VALUES (24, 'senior executive');
INSERT INTO ojp.designations (designation_id, designation) VALUES (25, 'hR Manager');
INSERT INTO ojp.designations (designation_id, designation) VALUES (26, 'senior HR Manager');
INSERT INTO ojp.designations (designation_id, designation) VALUES (27, 'aVP');
INSERT INTO ojp.designations (designation_id, designation) VALUES (28, 'vP');
INSERT INTO ojp.designations (designation_id, designation) VALUES (29, 'cFO(Chief Financial Officer)');
INSERT INTO ojp.designations (designation_id, designation) VALUES (30, 'accountant');
INSERT INTO ojp.designations (designation_id, designation) VALUES (31, 'senior Accountant');
INSERT INTO ojp.designations (designation_id, designation) VALUES (32, 'manager');
INSERT INTO ojp.designations (designation_id, designation) VALUES (33, 'senior Manager');
INSERT INTO ojp.designations (designation_id, designation) VALUES (34, 'aVP');
INSERT INTO ojp.designations (designation_id, designation) VALUES (35, 'vP');
INSERT INTO ojp.designations (designation_id, designation) VALUES (36, 'cFO');