INSERT INTO ojp.cities (city_id, city, state_id) VALUES (1, 'indore', 1);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (2, 'bhopal', 1);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (3, 'gwalior', 1);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (4, 'kanpur', 2);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (5, 'allahabad', 2);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (6, 'luckhnow', 2);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (7, 'Visakhapatnam', 3);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (8, 'Vijayawada', 3);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (9, 'Krishna', 3);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (10, 'Guntur', 3);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (11, 'Nellore', 3);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (12, 'srinagar', 4);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (13, 'kashmir', 4);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (14, 'jammu', 4);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (15, 'tempe', 5);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (16, 'messa', 5);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (17, 'flagstaff', 5);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (18, 'Austin', 6);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (19, 'Dallas', 6);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (20, 'San Antonio', 6);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (21, 'Houston', 6);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (22, 'Lubbock', 6);
INSERT INTO ojp.cities (city_id, city, state_id) VALUES (23, 'El Paso', 6);